fix: remove netlify-cms support temporarily
An error occurs during build time:
Error: ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered

Possible causes:
https://github.com/gatsbyjs/gatsby/pull/34413